version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_lead_api
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - lead-network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_fpm_lead_api
    volumes:
      - ./:/var/www/html
    environment:
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG}"
      APP_URL: "${APP_URL}"
      LOG_CHANNEL: "${LOG_CHANNEL}"
      LOG_DEPRECATIONS_CHANNEL: "${LOG_DEPRECATIONS_CHANNEL}"
      LOG_LEVEL: "${LOG_LEVEL}"
      DB_CONNECTION: "${DB_CONNECTION}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      LOG_DB_HOST: "${LOG_DB_HOST}"
      LOG_DB_PORT: "${LOG_DB_PORT}"
      LOG_DB_DATABASE: "${LOG_DB_DATABASE}"
      LOG_DB_USERNAME: "${LOG_DB_USERNAME}"
      LOG_DB_PASSWORD: "${LOG_DB_PASSWORD}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: "${REDIS_PORT}"
      API_BEARER_TOKEN: "${API_BEARER_TOKEN}"
      THIRD_PARTY_API_URL: "${THIRD_PARTY_API_URL}"
      THIRD_PARTY_API_KEY: "${THIRD_PARTY_API_KEY}"
      APP_CORS_ALLOWED_ORIGINS: "${APP_CORS_ALLOWED_ORIGINS}"
    networks:
      - lead-network
    depends_on:
      - pgsql_leads_db
      - pgsql_error_logs_db
      - redis_cache
      
  pgsql_leads_db:
    image: postgres:15-alpine
    container_name: pgsql_leads_db
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_leads_data:/var/lib/postgresql/data
      - ./init-leads-db.sql:/docker-entrypoint-initdb.d/init-leads-db.sql
    ports:
      - "5432:5432" 
    networks:
      - lead-network

  pgsql_error_logs_db:
    image: postgres:15-alpine
    container_name: pgsql_error_logs_db
    environment:
      POSTGRES_DB: "${LOG_DB_DATABASE}"
      POSTGRES_USER: "${LOG_DB_USERNAME}"
      POSTGRES_PASSWORD: "${LOG_DB_PASSWORD}"
    volumes:
      - db_error_logs_data:/var/lib/postgresql/data
      - ./init-error-logs-db.sql:/docker-entrypoint-initdb.d/init-error-logs-db.sql
    ports:
      - "5433:5432" 
    networks:
      - lead-network

  redis_cache:
    image: redis:alpine
    container_name: redis_lead_api_cache
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379" 
    networks:
      - lead-network

  wordpress:
    image: wordpress:latest
    container_name: wordpress_lead_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mysql_wordpress_db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html  # <-- Bind mount for local development
    depends_on:
      - mysql_wordpress_db
      - nginx
    ports:
      - "8080:80"
    networks:
      - lead-network

  mysql_wordpress_db:
    image: mysql:8.0
    container_name: mysql_wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_wordpress_data:/var/lib/mysql
    networks:
      - lead-network

networks:
  lead-network:
    driver: bridge

volumes:
  db_leads_data:
  db_error_logs_data:
  redis_data:
  db_wordpress_data: